### ISSUE TITLE
Unsupported callback API version 에러가 발생합니다.

### ISSUE THREAD

**Issue by HanXHoon** [djjproject/dawon_css_server_ha_bridge#2]
안녕하세요, 프로그램 잘 사용하고있습니다.
정말 감사드립니다.

2024년 2월 10일 paho-mqtt가 2.0.0버전으로 업데이트되면서
paho-mqtt 라이브러리 버전을 명시하지않고 최신버전을 설치 시 에러가 발생합니다.
```
Traceback (most recent call last):
  File "/share/dawon_css_server_bridge/bridge.py", line 166, in <module>
    client = connect_mqtt(mqtt_clientid, mqtt_username, mqtt_password, mqtt_host, mqtt_port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/dawon_css_server_bridge/bridge.py", line 21, in connect_mqtt
    client = mqtt.Client(client_id, clean_session=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 766, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details
```

bridge.py파일 21번라인의 mqtt.Client 인스턴스 생성 파라미터가 변경되어서 에러가 발생하는 듯 합니다.

paho-mqtt 라이브러리 설치 시 버전을 명시해 1.6.1버전을 설치하거나,
(1.6.1버전이 2.0.0버전 미만에서 최신입니다.)
```
pip install paho-mqtt==1.6.1
```

임시지만 bridge.py 파일의 21번 라인

```
client = mqtt.Client(client_id, clean_session=False)
```
를
```
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1, client_id, clean_session=False)
```
로 바꾸면 해결됩니다.
(프로그램 실행할 때 deprecated 될 예정이니 바꾸라고 warning이 뜹니다.)

**Comment by djjproject** [comment]
안녕하세요? 알려주신 부분 수정하여 조만간 반영하도록 하겠습니다.
감사합니다.
